### PR TITLE
Deploy beamline services to new namespace

### PR DESCRIPTION
**Pull request by DiamondJoseph**

### CODE REVIEW

**Comment by DiamondJoseph** [comment]
Does this need apps.yaml namespace to change?
Ingresses for rabbitmq and blueapi are currently created in this namespace, can we just move over or do we need to request new cloud team actions?
Switching the namespace should remove all of the old applications and redeploy in new namespace, but will it do all required cleanup?

Blocked because need SealedSecret to be generated in new namespace

**Comment by gilesknap** [comment]
@DiamondJoseph this is a fun PR. We do also need to change the apps.yaml namespace because bl45p namespace app will not have permission to deploy to bl45p-beamline.

For this reason we can't have argo do the whole transfer for us. When you are ready with the sealed secret. You can:

- go to the argocd Web UI and delete the root app
- change apps.yaml to namespace bl45p-beamline
- merge the changes into main
- kubectl apply -n bl45p-beamline apps.yaml

Out newly namespaced beamline will burst into life. Probably.

**Comment by marcelldls** [comment]
The epics helm charts that are being used are now consistent with the other test beamlines and everything appears to be running OK. Note: I haven't touched the actual ioc configs.

**Comment by gilesknap** [comment]
@marcelldls I think we should take this opportunity to update the iocs values.yaml to point at the latest versions of the generic IOCs. 

This is something that I think is not super slick to do right now - do we want to make some tooling to do this? can you let me know what you think?

**Comment by marcelldls** [comment]
@gilesknap fair enough. The services, deployment repos for bl45p is not exactly consistent with any other beamline (experimental?) so I was trying to not do more than I need to, also PRs into the deployment repo is a bit of a pain. 

As for tooling - I believe you have mentioned this as a possible feature for `ec` in the past. I reckon up reving `ghcr.io/epics-containers/xxx` in any of our values.yaml seems easy/useful?

**Comment by gilesknap** [comment]
Yes up revving is what I'm suggesting. We don't have a strong need to update the IOCs right now.

**Comment by gilesknap** [comment]
@DiamondJoseph are we ready to pull the trigger on this yet? I'm happy to facilitate the transfer once you are ready.

**Comment by DiamondJoseph** [comment]
@gilesknap I can't think of what was/is stopping us, so I say go for it and we'll find out.
https://github.com/epics-containers/p45-services/pull/31 for the change to the SealedSecret that is required at the same time

**Comment by gilesknap** [comment]
closing this as I have made the necessary changes in #15

**Pull request closed without merging**
